packaging_format = 2

id = "swingmusic"
name = "Swing Music"
description.en = "Beautiful music player for your local audio files"
description.fr = "Magnifique lecteur de musique pour vos fichiers audios locaux"

version = "2.0.1~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://swingmx.com/"
admindoc = "https://swingmx.com/guide/getting-started.html"
code = "https://github.com/swingmx/swingmusic"

[integration]
yunohost = ">= 12.1.1"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/swingmx/swingmusic/releases/download/v2.0.1/swingmusic_linux_amd64"
        sha256 = "7bd84febe73e60598511b9e11d6481b80add65be4ece3d5de9b9e7e015d207c5"
        extract = false
        rename = "swingmusic"

        autoupdate.strategy = "latest_github_tag"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ["ffmpeg", "libavcodec-extra"]